### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by agrytsenko**
Added missing packages to setup.py

### CODE REVIEW

**Comment by agrytsenko** [comment]
I've still got 'kvkit.tests.backends' and  'kvkit.tests.properties' dirs missing

**Comment by shuhaowu** [comment]
What's the exact issue you're having?

**Comment by agrytsenko** [comment]
First of all - thanks for implementing this library and sharing the code. You did a great job!

Issues are:
-  You can not install 'kvkit' via pip because it is not in packages list
-  When you install the 'kvkit' directly from github it installs only top-level modules, without properties/, backends/ etc.. 

Example:

```
# pip install git+https://github.com/shuhaowu/kvkit.git@master
...
# ls -l /path/to/site-packages/kvkit/
document.py
emdocument.py
exceptions.py
helpers.py
__init__.py
```

In order to install it i had to clone the repo. 

Please also note that my fix above is still missing 'tests/' dir, but i have noticed it later, after i pushed the request

**Comment by shuhaowu** [comment]
Thanks for explaining the issue! I'm currently out and having some trouble with ssh connections to github. I'll confirm once I get a better connection. I have done similar things before but it definitely worked for me.

One note: do the tests directory need to be included?

**Comment by shuhaowu** [comment]
Confirmed. 

Thanks!

**Pull request merged**
